FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG PORT
ENV PORT=${PORT}

FROM node:lts-alpine

COPY --from=builder /app ./

EXPOSE $PORT

CMD ["node", "server.js"]